feat: break class list with quotes on new lines
kalimahapps/eslint-plugin-tailwind pull request #4
Opened 2023-07-11 14:02 UTC by pglaum

I think it is cleaner, when the classes are all in their own line. So the quotes are on different lines than the classes.
(This also makes it easier to yank/paste classes in vim, for example.)

Before:

```html
<template>
         <div class="text-red-500
                 text-blue-500
                 text-green-500
                 text-yellow-500"
         ></div>
</template>
```

After:

```html
<template>
         <div class="
                 text-red-500
                 text-blue-500
                 text-green-500
                 text-yellow-500
                 "
         ></div>
</template>
```

2023-07-11 21:14 UTC, abdul-alhasany commented
It looks good. I was hesitant to include this when I made the plugin because it adds unexpected whitespace. For example it was a single line and formatted into multi line.

I don't have an issue adding this feature but I prefer it behind an option since it is a breaking change now.

Maybe we can call the option, whitespaceEnvlop? I don't mind any name as long as documentation is added.

2023-07-12 06:52 UTC, pglaum commented
Ok, I did that. When you merge the other pull request, I can rebase this one, update the tests with spaces & bump the version.

2023-07-17 15:45 UTC, abdul-alhasany commented
It looks good. Please bump the version so I can merge it.

2023-07-17 15:49 UTC, abdul-alhasany requested changes

2023-07-17 15:49 UTC, abdul-alhasany commented on readme.md
> +- `quotesOnNewLine`: put the quotes on different lines as the first and last class
Looks good. I think `as` should be `to`. 
different lines **to** the first and ..

2023-07-18 15:17 UTC, merged